name: Build Meteor Addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Bước 3: Phân quyền và build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # Bước 4: Upload file JAR
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meteor-addon
          path: build/libs/*.jar
