name: Build Meteor Addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cài Gradle 7.6 (nếu repo chưa có wrapper)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      # 4. Build
      - name: Build addon
        run: gradle clean build

      # 5. Upload file JAR
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meteor-addon
          path: build/libs/*.jar
